---
title: "Pokemon Web Scraper"
output: html_notebook
---


```{r Libraries}
    # General-purpose data wrangling
    library(tidyverse)  

    # Parsing of HTML/XML files  
    library(rvest)    

    # String manipulation
    library(stringr)   

    # Eases DateTime manipulation
    library(lubridate)
```

```{r Scrape page}

url <- "https://pokemondb.net/pokedex/all"
webpage <- read_html(url)
```

Find the maximum number of pages to be queried
Generate all the subpages that make up the reviews
Scrape the information from each of them
Combine the information into one comprehensive data frame

```{r All info}
pokemon_html <- html_nodes(webpage,".cell-num , .cell-total , .cell-name")

pokemon <- html_text(pokemon_html)
```


```{r Pokemon numbers}

poke_nums_html <- html_nodes(webpage,".cell-fixed")

poke_nums <- html_text(poke_nums_html)

head(poke_nums)

```

```{r Pokemon names}
poke_names_html <- html_nodes(webpage, ".cell-name")

poke_names <- html_text(poke_names_html)

head(poke_names)
```

```{r Pokemon BST}

poke_total_html <- html_nodes(webpage, ".cell-total")

poke_total <- html_text(poke_total_html)


```


```{r Combine into a dataframe}
pokemon_df <- data.frame(Number = poke_nums,Name = poke_names, BST = poke_total)

head(pokemon_df)

```

